# Make checks the timestamps of the target file ("code01") and its dependency ("code01.c").
# File code01.c is the dependency rule so that make will run again.
code01: code01.c
	gcc -o code01 code01.c
	./code01
