code01:
	gcc -o code-01 code-01.c
	./code-01

code02:
	gcc -o code-02 code-02.c
	./code-02

code03:
	gcc -o code-03 code-03.c
	./code-03

code04:
	gcc -o code-04 code-04.c
	./code-04

code05:
	gcc -o code-05 code-05.c
	./code-05

code06:
	gcc -o code-06 code-06.c
	./code-06

code07:
	gcc -g -o code-07 code-07.c
	./code-07

code08:
	gcc -g -o code-08 code-08.c
	./code-08
